const optimizationStyles=document.createElement('link');optimizationStyles.rel='stylesheet';optimizationStyles.href='optimizations.css';document.head.appendChild(optimizationStyles);
const style=document.createElement('style');style.textContent='.site-header .brand-logo{background:transparent!important;padding:0!important;border-radius:0!important;box-shadow:none!important}.footer-logo{background:transparent!important;padding:0!important;border-radius:0!important;box-shadow:none!important}';document.head.appendChild(style);

function closeLegacyNavigation(){const toggle=document.querySelector('.mobile-toggle');const nav=document.querySelector('.nav-links');if(toggle&&nav&&nav.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Open menu');}}

function wireLegacyNavigation(){const toggle=document.querySelector('.mobile-toggle');const nav=document.querySelector('.nav-links');if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close menu':'Open menu');});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',closeLegacyNavigation));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav.classList.contains('open')){closeLegacyNavigation();toggle.focus();}});document.addEventListener('click',event=>{if(nav.classList.contains('open')&&!nav.contains(event.target)&&!toggle.contains(event.target))closeLegacyNavigation();});}}

function markCurrentPage(){const current=window.location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a,.footer-bottom a').forEach(link=>{const href=(link.getAttribute('href')||'').split('#')[0];if(href&&href===current)link.setAttribute('aria-current','page');});}

function addMobileActionBar(){if(document.querySelector('.mobile-action-bar'))return;const bar=document.createElement('nav');bar.className='mobile-action-bar';bar.setAttribute('aria-label','Quick actions');bar.innerHTML='<a class="mobile-action-call" href="tel:+15093026024" aria-label="Call All Things Drywall and Construction at 509-302-6024">Call</a><a class="mobile-action-estimate" href="contact.html">Request Estimate</a>';document.body.appendChild(bar);}

function improveImages(root=document){root.querySelectorAll('img').forEach((img,index)=>{img.decoding='async';if(index>0&&!img.closest('.hero'))img.loading='lazy';});}

function loadScript(src){return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.crossOrigin='anonymous';script.onload=resolve;script.onerror=reject;document.head.appendChild(script);});}

async function mountReactLayout(){try{if(!window.React)await loadScript('https://unpkg.com/react@18.3.1/umd/react.production.min.js');if(!window.ReactDOM)await loadScript('https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js');await loadScript('components.js');requestAnimationFrame(()=>{markCurrentPage();improveImages();});return true;}catch(error){console.warn('Shared React components could not load; using static page layout.',error);return false;}}

wireLegacyNavigation();markCurrentPage();addMobileActionBar();improveImages();window.allThingsReactReady=mountReactLayout();

const form=document.querySelector('[data-contact-form]');if(form){form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const submit=form.querySelector('button[type="submit"]');const original=submit?.textContent;if(submit){submit.disabled=true;submit.setAttribute('aria-busy','true');submit.textContent='Opening email…';}const subject=encodeURIComponent('Estimate Request — '+(data.get('name')||'Website'));const body=encodeURIComponent(`Name: ${data.get('name')||''}\nPhone: ${data.get('phone')||''}\nEmail: ${data.get('email')||''}\n\nProject details:\n${data.get('message')||''}`);window.location.href=`mailto:matt@allthingsdac.com?subject=${subject}&body=${body}`;setTimeout(()=>{if(submit){submit.disabled=false;submit.setAttribute('aria-busy','false');submit.textContent=original||'Email Estimate Request';}},900);});}
