const THEME_MANIFEST_PATH='site-theme.json';
const THEME_CSS_PATH='site-theme.css';
const DEFAULT_THEME={
 topbarBackground:'#24372d',
 headerBackground:'#151a17',
 primaryButton:'#a9462c',
 primaryButtonHover:'#7e321f',
 ctaBackground:'#24372d',
 footerBackground:'#111512',
 pageBannerBackground:'#f4f5f3',
 pageBackground:'#ffffff',
 textColor:'#171a1d',
 mutedTextColor:'#667078'
};
const THEME_KEYS=Object.keys(DEFAULT_THEME);
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
function cleanColor(value,fallback){const color=String(value||'').trim().toLowerCase();return /^#[0-9a-f]{6}$/.test(color)?color:fallback;}
function cleanTheme(input){const source=input&&typeof input==='object'&&!Array.isArray(input)?input:{};const output={};for(const key of THEME_KEYS)output[key]=cleanColor(source[key],DEFAULT_THEME[key]);return output;}
function githubConfig(env){return{token:String(env.GITHUB_SITE_IMAGES_TOKEN||env.GITHUB_TOKEN||'').trim(),owner:String(env.GITHUB_SITE_IMAGES_OWNER||'zlharrington').trim(),repo:String(env.GITHUB_SITE_IMAGES_REPO||'allthingsdac').trim(),branch:String(env.GITHUB_SITE_IMAGES_BRANCH||'main').trim()};}
async function githubApi(env,path,{method='GET',body}={}){const cfg=githubConfig(env);if(!cfg.token)throw Object.assign(new Error('GitHub site management token is not configured in Cloudflare.'),{status:503});const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(cfg.owner)}/${encodeURIComponent(cfg.repo)}${path}`,{method,headers:{authorization:`Bearer ${cfg.token}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'allthingsdac-theme-worker','x-github-api-version':'2022-11-28'},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let data={};if(text){try{data=JSON.parse(text);}catch{data={message:text};}}if(!response.ok)throw Object.assign(new Error(data.message||`GitHub request failed (${response.status}).`),{status:response.status});return data;}
function themeCss(theme){return `/* Managed by the admin Site Theme / Color Manager. */\n:root{\n  --theme-topbar-background:${theme.topbarBackground};\n  --theme-header-background:${theme.headerBackground};\n  --theme-primary-button:${theme.primaryButton};\n  --theme-primary-button-hover:${theme.primaryButtonHover};\n  --theme-cta-background:${theme.ctaBackground};\n  --theme-footer-background:${theme.footerBackground};\n  --theme-page-banner-background:${theme.pageBannerBackground};\n  --theme-page-background:${theme.pageBackground};\n  --theme-text-color:${theme.textColor};\n  --theme-muted-text-color:${theme.mutedTextColor};\n  --accent:var(--theme-primary-button);\n  --accent-dark:var(--theme-primary-button-hover);\n  --forest:var(--theme-topbar-background);\n  --header:var(--theme-header-background);\n  --paper:var(--theme-page-background);\n  --ink:var(--theme-text-color);\n  --muted:var(--theme-muted-text-color);\n  --soft:var(--theme-page-banner-background);\n}\nbody{background:var(--theme-page-background);color:var(--theme-text-color)}\n.topbar{background:var(--theme-topbar-background)}\n.site-header{background:var(--theme-header-background)}\n@media(max-width:850px){.nav-links{background:var(--theme-header-background)}}\n.btn-primary,.mobile-action-estimate{background:var(--theme-primary-button);border-color:var(--theme-primary-button)}\n.btn-primary:hover,.btn-primary:focus-visible,.mobile-action-estimate:hover,.mobile-action-estimate:focus-visible{background:var(--theme-primary-button-hover);border-color:var(--theme-primary-button-hover)}\n.cta,.trust-strip{background:var(--theme-cta-background)}\n.footer{background:var(--theme-footer-background)}\n.page-hero{background:var(--theme-page-banner-background)}\n.section-head p,.card p,.split p,.service-feature p,.project-card p,.person p,.stat span,.photo-note,.page-hero p{color:var(--theme-muted-text-color)}\n`;}
async function commitThemeAttempt(env,theme,adminUser){const cfg=githubConfig(env);const ref=await githubApi(env,`/git/ref/heads/${cfg.branch}`),parentSha=ref.object?.sha;if(!parentSha)throw new Error('GitHub branch reference could not be resolved.');const parentCommit=await githubApi(env,`/git/commits/${parentSha}`),baseTree=parentCommit.tree?.sha;if(!baseTree)throw new Error('GitHub base tree could not be resolved.');const manifestBlob=await githubApi(env,'/git/blobs',{method:'POST',body:{content:JSON.stringify(theme,null,2)+'\n',encoding:'utf-8'}});const cssBlob=await githubApi(env,'/git/blobs',{method:'POST',body:{content:themeCss(theme),encoding:'utf-8'}});const tree=await githubApi(env,'/git/trees',{method:'POST',body:{base_tree:baseTree,tree:[{path:THEME_MANIFEST_PATH,mode:'100644',type:'blob',sha:manifestBlob.sha},{path:THEME_CSS_PATH,mode:'100644',type:'blob',sha:cssBlob.sha}]}});const commit=await githubApi(env,'/git/commits',{method:'POST',body:{message:'Update website color theme',tree:tree.sha,parents:[parentSha],author:{name:String(adminUser||'All Things DAC Admin').slice(0,80),email:'site-admin@allthingsdac.com'}}});await githubApi(env,`/git/refs/heads/${cfg.branch}`,{method:'PATCH',body:{sha:commit.sha,force:false}});return commit.sha;}
async function commitTheme(env,theme,adminUser){let error;for(let attempt=0;attempt<3;attempt++){try{return await commitThemeAttempt(env,theme,adminUser);}catch(err){error=err;if(err.status!==409||attempt===2)throw err;await new Promise(resolve=>setTimeout(resolve,120*(attempt+1)));}}throw error;}
export async function handleAdminTheme(request,env,adminUser){if(request.method!=='POST')return new Response('Method not allowed',{status:405,headers:{allow:'POST'}});let body;try{body=await request.json();}catch{return json({error:'Invalid theme request.'},400);}const theme=cleanTheme(body.theme);try{const commitSha=await commitTheme(env,theme,adminUser);return json({ok:true,theme,commitSha});}catch(error){return json({error:error.message||'Theme update failed.'},error.status>=400&&error.status<600?error.status:502);}}
