(()=>{
const schema=window.DAC_PAGE_SCHEMA;if(!schema)return;
const header=document.querySelector('.admin-head');const existingPanels=[...document.querySelectorAll('.admin-shell > .admin-panel')];if(!header||!existingPanels.length)return;
const tabs=document.createElement('nav');tabs.className='admin-tabs';tabs.setAttribute('aria-label','Admin sections');
const galleryPanel=document.createElement('div');galleryPanel.className='admin-tab-panel active';galleryPanel.dataset.tabPanel='gallery';existingPanels[0].before(galleryPanel);existingPanels.forEach(panel=>galleryPanel.appendChild(panel));
const entries=[['gallery',{label:'Projects & Photos'}],...Object.entries(schema)];
for(const [key,page] of entries){const button=document.createElement('button');button.type='button';button.className='admin-tab-button'+(key==='gallery'?' active':'');button.dataset.tab=key;button.textContent=page.label;button.setAttribute('aria-selected',key==='gallery'?'true':'false');tabs.appendChild(button);if(key!=='gallery'){const panel=document.createElement('section');panel.className='admin-tab-panel';panel.dataset.tabPanel=key;panel.innerHTML=`<div class="admin-panel page-editor-shell"><div class="page-editor-head"><div><span class="eyebrow">Page editor</span><h2>${escapeHtml(page.label)}</h2><p>Update the text and images shown on this page. Changes are saved without editing website code.</p></div><a class="btn btn-outline" href="../${escapeHtml(page.file)}" target="_blank" rel="noopener">Open page</a></div><div class="page-editor-loading">Loading page fields…</div></div>`;galleryPanel.after(panel);}}
header.after(tabs);
const loaded=new Set();
tabs.addEventListener('click',event=>{const button=event.target.closest('.admin-tab-button');if(!button)return;activate(button.dataset.tab);});
function activate(key){document.querySelectorAll('.admin-tab-button').forEach(button=>{const on=button.dataset.tab===key;button.classList.toggle('active',on);button.setAttribute('aria-selected',String(on));});document.querySelectorAll('.admin-tab-panel').forEach(panel=>panel.classList.toggle('active',panel.dataset.tabPanel===key));if(key!=='gallery'&&!loaded.has(key))loadEditor(key);}
async function requestJson(url,options){const response=await fetch(url,options);const text=await response.text();let data={};if(text){try{data=JSON.parse(text);}catch{data={error:text};}}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function readDefault(doc,field){const el=doc.querySelector(field.selector);if(!el)return '';if(field.type==='image')return el.getAttribute('src')||'';if(field.attr)return el.getAttribute(field.attr)||'';return (el.textContent||'').trim();}
async function loadEditor(key){const page=schema[key];const panel=document.querySelector(`[data-tab-panel="${key}"] .page-editor-shell`);if(!page||!panel)return;try{const [htmlResponse,saved]=await Promise.all([fetch(`../${page.file}`,{cache:'no-store'}),requestJson(`/api/admin/site-content?page=${encodeURIComponent(key)}`)]);if(!htmlResponse.ok)throw new Error(`Could not load ${page.file}.`);const doc=new DOMParser().parseFromString(await htmlResponse.text(),'text/html');const defaults={};page.fields.forEach(field=>defaults[field.key]=readDefault(doc,field));renderEditor(key,page,panel,defaults,saved.content||{});loaded.add(key);}catch(error){panel.querySelector('.page-editor-loading').textContent=error.message;}}
function renderEditor(key,page,panel,defaults,saved){const groups=[];for(const field of page.fields){let group=groups.find(item=>item.name===(field.group||'Page content'));if(!group){group={name:field.group||'Page content',fields:[]};groups.push(group);}group.fields.push(field);}const fieldsHtml=groups.map(group=>`<fieldset class="page-editor-group"><legend>${escapeHtml(group.name)}</legend>${group.fields.map(field=>fieldHtml(field,saved[field.key]??defaults[field.key]??'')).join('')}</fieldset>`).join('');panel.querySelector('.page-editor-loading').outerHTML=`<form class="page-editor-form" data-page-key="${escapeHtml(key)}">${fieldsHtml}<div class="page-editor-actions"><button class="btn btn-primary" type="submit">Save ${escapeHtml(page.label)}</button><button class="btn btn-outline reset-page-content" type="button">Restore original page content</button></div><p class="admin-status page-editor-status" role="status" aria-live="polite"></p></form>`;wireImagePreviews(panel);}
function fieldHtml(field,value){if(field.type==='image'){return `<label class="page-editor-field image-field"><span>${escapeHtml(field.label)}</span><div class="image-editor-row"><img class="page-image-preview" src="${escapeHtml(value)}" alt="${escapeHtml(field.label)} preview"><div><input type="hidden" data-content-field="${escapeHtml(field.key)}" value="${escapeHtml(value)}"><input type="file" data-image-field="${escapeHtml(field.key)}" accept="image/jpeg,image/png,image/webp,image/avif"><small>Choose a new image to replace the current one. JPG, PNG, WebP or AVIF, up to 15 MB.</small></div></div></label>`;}const tag=field.multiline?'textarea':'input';return `<label class="page-editor-field"><span>${escapeHtml(field.label)}</span>${tag==='textarea'?`<textarea data-content-field="${escapeHtml(field.key)}" rows="4">${escapeHtml(value)}</textarea>`:`<input data-content-field="${escapeHtml(field.key)}" type="text" value="${escapeHtml(value)}">`}</label>`;}
function wireImagePreviews(panel){panel.querySelectorAll('[data-image-field]').forEach(input=>input.addEventListener('change',()=>{const file=input.files?.[0];if(!file)return;const preview=input.closest('.image-editor-row')?.querySelector('.page-image-preview');if(preview)preview.src=URL.createObjectURL(file);}));}
document.addEventListener('submit',async event=>{const form=event.target.closest('.page-editor-form');if(!form)return;event.preventDefault();const key=form.dataset.pageKey;const page=schema[key];const status=form.querySelector('.page-editor-status');const submit=form.querySelector('button[type="submit"]');submit.disabled=true;status.classList.remove('error');status.textContent='Saving page…';try{for(const fileInput of form.querySelectorAll('[data-image-field]')){const file=fileInput.files?.[0];if(!file)continue;status.textContent=`Uploading ${file.name}…`;const body=new FormData();body.set('file',file);body.set('page',key);body.set('field',fileInput.dataset.imageField);const uploaded=await requestJson('/api/admin/site-image',{method:'POST',body});const hidden=form.querySelector(`[data-content-field="${fileInput.dataset.imageField}"]`);hidden.value=uploaded.url;const preview=fileInput.closest('.image-editor-row')?.querySelector('.page-image-preview');if(preview)preview.src=uploaded.url;fileInput.value='';}const content={};form.querySelectorAll('[data-content-field]').forEach(input=>content[input.dataset.contentField]=input.value);await requestJson(`/api/admin/site-content?page=${encodeURIComponent(key)}`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({content})});status.textContent=`${page.label} page saved.`;}catch(error){status.textContent=error.message;status.classList.add('error');}finally{submit.disabled=false;}});
document.addEventListener('click',async event=>{const button=event.target.closest('.reset-page-content');if(!button)return;const form=button.closest('.page-editor-form');const key=form?.dataset.pageKey;if(!key||!confirm('Restore this page to the original website text and images?'))return;button.disabled=true;const status=form.querySelector('.page-editor-status');try{await requestJson(`/api/admin/site-content?page=${encodeURIComponent(key)}`,{method:'DELETE'});loaded.delete(key);const panel=document.querySelector(`[data-tab-panel="${key}"] .page-editor-shell`);panel.innerHTML=`<div class="page-editor-head"><div><span class="eyebrow">Page editor</span><h2>${escapeHtml(schema[key].label)}</h2><p>Update the text and images shown on this page. Changes are saved without editing website code.</p></div><a class="btn btn-outline" href="../${escapeHtml(schema[key].file)}" target="_blank" rel="noopener">Open page</a></div><div class="page-editor-loading">Reloading original content…</div>`;await loadEditor(key);}catch(error){status.textContent=error.message;status.classList.add('error');}finally{button.disabled=false;}});
})();
