(()=>{
const DEFAULT_THEME={topbarBackground:'#5f7484',headerBackground:'#50697a',primaryButton:'#a85f48',primaryButtonHover:'#7f4634',ctaBackground:'#536e7d',footerBackground:'#2e434f',pageBannerBackground:'#e8f0f4',pageBackground:'#f8fbfc',textColor:'#20303a',mutedTextColor:'#5b6c76'};
const PRESETS=[
 {key:'harbor',name:'Harbor Blue',description:'Recommended · cool blue-gray with a restrained clay accent.',theme:{topbarBackground:'#5f7484',headerBackground:'#50697a',primaryButton:'#a85f48',primaryButtonHover:'#7f4634',ctaBackground:'#536e7d',footerBackground:'#2e434f',pageBannerBackground:'#e8f0f4',pageBackground:'#f8fbfc',textColor:'#20303a',mutedTextColor:'#5b6c76'}},
 {key:'steel-copper',name:'Steel & Copper',description:'Industrial steel blues with a warmer copper action color.',theme:{topbarBackground:'#617584',headerBackground:'#455e6f',primaryButton:'#a55c43',primaryButtonHover:'#7b4331',ctaBackground:'#607786',footerBackground:'#293d49',pageBannerBackground:'#e7eef2',pageBackground:'#fcfdfd',textColor:'#202d34',mutedTextColor:'#60717a'}},
 {key:'mist-navy',name:'Mist & Navy',description:'Clean cool grays with a deeper blue accent for a more corporate look.',theme:{topbarBackground:'#627682',headerBackground:'#4b6477',primaryButton:'#345e7a',primaryButtonHover:'#24465c',ctaBackground:'#526d80',footerBackground:'#263b49',pageBannerBackground:'#eef4f7',pageBackground:'#fbfdfe',textColor:'#203039',mutedTextColor:'#61727c'}},
 {key:'glacier-sage',name:'Glacier & Sage',description:'Blue-gray foundation softened with a muted sage-green accent.',theme:{topbarBackground:'#667a7f',headerBackground:'#4e686d',primaryButton:'#5f7669',primaryButtonHover:'#485c51',ctaBackground:'#5b7478',footerBackground:'#2e4245',pageBannerBackground:'#edf3f2',pageBackground:'#fbfcfc',textColor:'#253538',mutedTextColor:'#64767a'}},
 {key:'blueprint-bronze',name:'Blueprint & Bronze',description:'Structured blueprint blues with a subdued bronze highlight.',theme:{topbarBackground:'#637785',headerBackground:'#496274',primaryButton:'#8a6544',primaryButtonHover:'#694c33',ctaBackground:'#556f80',footerBackground:'#293e4b',pageBannerBackground:'#eaf1f5',pageBackground:'#fafcfd',textColor:'#21313a',mutedTextColor:'#5f707b'}}
];
const TARGETS=[
 ['topbarBackground','Top banner background'],
 ['headerBackground','Header / navigation background'],
 ['primaryButton','Primary buttons'],
 ['primaryButtonHover','Primary button hover'],
 ['ctaBackground','CTA / trust banner background'],
 ['footerBackground','Footer background'],
 ['pageBannerBackground','Interior page banner background'],
 ['pageBackground','Main page background'],
 ['textColor','Main text'],
 ['mutedTextColor','Secondary / muted text']
];
let theme={...DEFAULT_THEME};
function validHex(value){return /^#[0-9a-f]{6}$/i.test(String(value||'').trim());}
async function requestJson(url,options){const response=await fetch(url,options);const text=await response.text();let data={};if(text){try{data=JSON.parse(text);}catch{data={error:text};}}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function sameTheme(a,b){return Object.keys(DEFAULT_THEME).every(key=>String(a?.[key]||'').toLowerCase()===String(b?.[key]||'').toLowerCase());}
function presetMarkup(preset){const swatches=[preset.theme.headerBackground,preset.theme.topbarBackground,preset.theme.primaryButton,preset.theme.ctaBackground,preset.theme.pageBannerBackground,preset.theme.footerBackground];return `<button class="theme-preset" type="button" data-theme-preset="${preset.key}" aria-pressed="false"><span class="theme-preset-title">${preset.name}</span><span class="theme-preset-swatches" aria-hidden="true">${swatches.map(color=>`<i style="background:${color}"></i>`).join('')}</span><small>${preset.description}</small></button>`;}
function buildPanel(){if(document.getElementById('themeManagerPanel'))return;const panel=document.createElement('section');panel.id='themeManagerPanel';panel.className='admin-panel';panel.innerHTML=`<div class="admin-section-head"><div><span class="eyebrow">Site appearance</span><h2>Color manager</h2><p>Apply a complete professional palette or fine-tune individual website areas.</p></div></div><div class="theme-manager-grid"><div><div class="theme-subhead"><strong>Preset palettes</strong><span>One click saves the whole palette to the website repo.</span></div><div class="theme-preset-grid">${PRESETS.map(presetMarkup).join('')}</div></div><div class="theme-divider"></div><div class="theme-subhead"><strong>Fine tune a color</strong><span>Adjust one area without changing the rest of the active palette.</span></div><label class="theme-field">Website area<select id="themeTarget">${TARGETS.map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label><div class="theme-picker-wrap"><label class="theme-field">Color<input id="themeColor" type="color" value="#5f7484" aria-label="Choose website color"></label><label class="theme-field">Hex color<input id="themeHex" type="text" value="#5f7484" maxlength="7" inputmode="text" spellcheck="false" aria-label="Hex color"></label><div class="theme-swatch" id="themeSwatch" aria-hidden="true"></div></div><div class="theme-actions"><button class="btn btn-primary" id="themeSave" type="button">Save selected color</button><button class="btn btn-outline" id="themeReset" type="button">Restore selected default</button></div><p class="admin-status" id="themeStatus" role="status" aria-live="polite"></p><small class="theme-help">Every preset or individual color change creates a GitHub commit updating <code>site-theme.json</code> and <code>site-theme.css</code>, matching the existing GitHub-backed site image workflow.</small></div>`;
 const style=document.createElement('style');style.textContent='.theme-manager-grid{display:grid;gap:18px}.theme-subhead{display:flex;align-items:baseline;justify-content:space-between;gap:16px;margin-bottom:10px}.theme-subhead strong{font-size:1rem}.theme-subhead span{color:var(--muted);font-size:.86rem}.theme-preset-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.theme-preset{min-height:132px;padding:14px;border:2px solid #d7dee3;border-radius:9px;background:#fff;text-align:left;cursor:pointer;font:inherit;transition:.16s ease}.theme-preset:hover{transform:translateY(-1px);border-color:#8fa4b1;box-shadow:0 7px 20px rgba(35,50,59,.08)}.theme-preset:focus-visible{outline:3px solid #a85f48;outline-offset:3px}.theme-preset[aria-pressed="true"]{border-color:#50697a;box-shadow:0 0 0 2px rgba(80,105,122,.15)}.theme-preset-title{display:block;font-weight:900;margin-bottom:9px}.theme-preset-swatches{display:grid;grid-template-columns:repeat(6,1fr);height:24px;overflow:hidden;border-radius:5px;border:1px solid rgba(0,0,0,.08);margin-bottom:9px}.theme-preset-swatches i{display:block}.theme-preset small{display:block;color:#65747d;line-height:1.35}.theme-divider{height:1px;background:#e1e6e3;margin:4px 0}.theme-field{display:grid;gap:7px;font-weight:800}.theme-field select,.theme-field input[type="text"]{min-height:46px;padding:10px 12px;border:1px solid #c9ceca;border-radius:6px;background:#fff;font:inherit}.theme-picker-wrap{display:grid;grid-template-columns:minmax(180px,.6fr) minmax(180px,.6fr) 88px;gap:14px;align-items:end}.theme-field input[type="color"]{width:100%;height:52px;padding:3px;border:1px solid #c9ceca;border-radius:6px;background:#fff;cursor:pointer}.theme-swatch{height:52px;border-radius:6px;border:1px solid #c9ceca;background:#5f7484}.theme-actions{display:flex;flex-wrap:wrap;gap:10px}.theme-help{color:var(--muted);line-height:1.5}.theme-help code{font-weight:800}@media(max-width:1100px){.theme-preset-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.theme-subhead{display:grid;gap:2px}.theme-preset-grid,.theme-picker-wrap{grid-template-columns:1fr}.theme-swatch{width:100%}}';document.head.appendChild(style);const anchor=document.querySelector('.admin-shell>section.admin-panel:last-of-type');if(anchor)anchor.after(panel);else document.querySelector('.admin-shell')?.appendChild(panel);wire(panel);loadTheme(panel);}
function selectedKey(panel){return panel.querySelector('#themeTarget').value;}
function syncControls(panel){const key=selectedKey(panel),value=theme[key]||DEFAULT_THEME[key];panel.querySelector('#themeColor').value=value;panel.querySelector('#themeHex').value=value;panel.querySelector('#themeSwatch').style.background=value;updatePresetState(panel);}
function updatePresetState(panel){panel.querySelectorAll('[data-theme-preset]').forEach(button=>{const preset=PRESETS.find(item=>item.key===button.dataset.themePreset);button.setAttribute('aria-pressed',String(Boolean(preset&&sameTheme(theme,preset.theme))));});}
function setStatus(panel,message,error=false){const status=panel.querySelector('#themeStatus');status.textContent=message;status.classList.toggle('error',error);}
function mergeThemeData(data){for(const key of Object.keys(DEFAULT_THEME))if(validHex(data?.[key]))theme[key]=String(data[key]).toLowerCase();}
async function loadTheme(panel){setStatus(panel,'Loading current website colors…');try{const response=await fetch(`/site-theme.json?v=${Date.now()}`,{cache:'no-store'});if(response.ok)mergeThemeData(await response.json());syncControls(panel);setStatus(panel,'Current website colors loaded.');}catch(error){syncControls(panel);setStatus(panel,'Using the default colors because the current theme could not be loaded.',true);}}
function setBusy(panel,busy){panel.querySelector('#themeSave').disabled=busy;panel.querySelector('#themeReset').disabled=busy;panel.querySelectorAll('[data-theme-preset]').forEach(button=>button.disabled=busy);}
async function saveTheme(panel,nextTheme,label){setBusy(panel,true);setStatus(panel,`Saving ${label} to GitHub…`);try{const result=await requestJson('/api/admin/theme',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme:nextTheme})});theme={...theme,...result.theme};syncControls(panel);setStatus(panel,`${label} saved. GitHub commit ${String(result.commitSha||'').slice(0,7)} created.`);}catch(error){setStatus(panel,error.message,true);}finally{setBusy(panel,false);}}
function wire(panel){const target=panel.querySelector('#themeTarget'),picker=panel.querySelector('#themeColor'),hex=panel.querySelector('#themeHex'),swatch=panel.querySelector('#themeSwatch'),save=panel.querySelector('#themeSave'),reset=panel.querySelector('#themeReset');target.addEventListener('change',()=>syncControls(panel));picker.addEventListener('input',()=>{hex.value=picker.value.toLowerCase();swatch.style.background=picker.value;});hex.addEventListener('input',()=>{const value=hex.value.trim();if(validHex(value)){picker.value=value;swatch.style.background=value;}});panel.querySelectorAll('[data-theme-preset]').forEach(button=>button.addEventListener('click',()=>{const preset=PRESETS.find(item=>item.key===button.dataset.themePreset);if(preset)saveTheme(panel,{...preset.theme},preset.name);}));save.addEventListener('click',()=>{const key=selectedKey(panel),value=hex.value.trim().toLowerCase();if(!validHex(value)){setStatus(panel,'Enter a six-digit hex color such as #a85f48.',true);hex.focus();return;}saveTheme(panel,{...theme,[key]:value},'Selected color');});reset.addEventListener('click',()=>{const key=selectedKey(panel),value=DEFAULT_THEME[key];picker.value=value;hex.value=value;swatch.style.background=value;setStatus(panel,'Default selected. Click “Save selected color” to commit it.');});}
async function enable(){let access=window.DAC_ADMIN_ACCESS;if(window.DAC_ADMIN_ACCESS_PROMISE)access=await window.DAC_ADMIN_ACCESS_PROMISE;const allowed=access?.role==='owner'||access?.permissions?.siteEditor===true;if(allowed)buildPanel();}
enable();
})();
