(()=>{
const DEFAULT_THEME={topbarBackground:'#24372d',headerBackground:'#151a17',primaryButton:'#a9462c',primaryButtonHover:'#7e321f',ctaBackground:'#24372d',footerBackground:'#111512',pageBannerBackground:'#f4f5f3',pageBackground:'#ffffff',textColor:'#171a1d',mutedTextColor:'#667078'};
const TARGETS=[
 ['topbarBackground','Top banner background'],
 ['headerBackground','Header / navigation background'],
 ['primaryButton','Primary buttons'],
 ['primaryButtonHover','Primary button hover'],
 ['ctaBackground','CTA / trust banner background'],
 ['footerBackground','Footer background'],
 ['pageBannerBackground','Interior page banner background'],
 ['pageBackground','Main page background'],
 ['textColor','Main text'],
 ['mutedTextColor','Secondary / muted text']
];
let theme={...DEFAULT_THEME};
function validHex(value){return /^#[0-9a-f]{6}$/i.test(String(value||'').trim());}
async function requestJson(url,options){const response=await fetch(url,options);const text=await response.text();let data={};if(text){try{data=JSON.parse(text);}catch{data={error:text};}}if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data;}
function buildPanel(){if(document.getElementById('themeManagerPanel'))return;const panel=document.createElement('section');panel.id='themeManagerPanel';panel.className='admin-panel';panel.innerHTML=`<div class="admin-section-head"><div><span class="eyebrow">Site appearance</span><h2>Color manager</h2><p>Choose an area of the website, pick a color, and save it directly to the GitHub-managed site theme.</p></div></div><div class="theme-manager-grid"><label class="theme-field">Website area<select id="themeTarget">${TARGETS.map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label><div class="theme-picker-wrap"><label class="theme-field">Color<input id="themeColor" type="color" value="#24372d" aria-label="Choose website color"></label><label class="theme-field">Hex color<input id="themeHex" type="text" value="#24372d" maxlength="7" inputmode="text" spellcheck="false" aria-label="Hex color"></label><div class="theme-swatch" id="themeSwatch" aria-hidden="true"></div></div><div class="theme-actions"><button class="btn btn-primary" id="themeSave" type="button">Save color to website</button><button class="btn btn-outline" id="themeReset" type="button">Restore selected default</button></div><p class="admin-status" id="themeStatus" role="status" aria-live="polite"></p><small class="theme-help">Saving creates a GitHub commit that updates <code>site-theme.json</code> and <code>site-theme.css</code>. The public site changes after the normal deployment completes.</small></div>`;
 const style=document.createElement('style');style.textContent='.theme-manager-grid{display:grid;gap:18px}.theme-field{display:grid;gap:7px;font-weight:800}.theme-field select,.theme-field input[type="text"]{min-height:46px;padding:10px 12px;border:1px solid #c9ceca;border-radius:6px;background:#fff;font:inherit}.theme-picker-wrap{display:grid;grid-template-columns:minmax(180px,.6fr) minmax(180px,.6fr) 88px;gap:14px;align-items:end}.theme-field input[type="color"]{width:100%;height:52px;padding:3px;border:1px solid #c9ceca;border-radius:6px;background:#fff;cursor:pointer}.theme-swatch{height:52px;border-radius:6px;border:1px solid #c9ceca;background:#24372d}.theme-actions{display:flex;flex-wrap:wrap;gap:10px}.theme-help{color:var(--muted);line-height:1.5}.theme-help code{font-weight:800}@media(max-width:700px){.theme-picker-wrap{grid-template-columns:1fr}.theme-swatch{width:100%}}';document.head.appendChild(style);const anchor=document.querySelector('.admin-shell>section.admin-panel:last-of-type');if(anchor)anchor.after(panel);else document.querySelector('.admin-shell')?.appendChild(panel);wire(panel);loadTheme(panel);}
function selectedKey(panel){return panel.querySelector('#themeTarget').value;}
function syncControls(panel){const key=selectedKey(panel),value=theme[key]||DEFAULT_THEME[key];panel.querySelector('#themeColor').value=value;panel.querySelector('#themeHex').value=value;panel.querySelector('#themeSwatch').style.background=value;}
function setStatus(panel,message,error=false){const status=panel.querySelector('#themeStatus');status.textContent=message;status.classList.toggle('error',error);}
async function loadTheme(panel){setStatus(panel,'Loading current website colors…');try{const response=await fetch('/site-theme.json',{cache:'no-store'});if(response.ok){const data=await response.json();for(const key of Object.keys(DEFAULT_THEME))if(validHex(data[key]))theme[key]=String(data[key]).toLowerCase();}syncControls(panel);setStatus(panel,'Current website colors loaded.');}catch(error){syncControls(panel);setStatus(panel,'Using the default colors because the current theme could not be loaded.',true);}}
function wire(panel){const target=panel.querySelector('#themeTarget'),picker=panel.querySelector('#themeColor'),hex=panel.querySelector('#themeHex'),swatch=panel.querySelector('#themeSwatch'),save=panel.querySelector('#themeSave'),reset=panel.querySelector('#themeReset');target.addEventListener('change',()=>syncControls(panel));picker.addEventListener('input',()=>{hex.value=picker.value.toLowerCase();swatch.style.background=picker.value;});hex.addEventListener('input',()=>{const value=hex.value.trim();if(validHex(value)){picker.value=value;swatch.style.background=value;}});save.addEventListener('click',async()=>{const key=selectedKey(panel),value=hex.value.trim().toLowerCase();if(!validHex(value)){setStatus(panel,'Enter a six-digit hex color such as #a9462c.',true);hex.focus();return;}theme[key]=value;save.disabled=true;reset.disabled=true;setStatus(panel,'Saving color to GitHub…');try{const result=await requestJson('/api/admin/theme',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({theme})});theme={...theme,...result.theme};syncControls(panel);setStatus(panel,`Saved. GitHub commit ${String(result.commitSha||'').slice(0,7)} created.`);}catch(error){setStatus(panel,error.message,true);}finally{save.disabled=false;reset.disabled=false;}});reset.addEventListener('click',()=>{const key=selectedKey(panel),value=DEFAULT_THEME[key];picker.value=value;hex.value=value;swatch.style.background=value;setStatus(panel,'Default selected. Click “Save color to website” to commit it.');});}
async function enable(){let access=window.DAC_ADMIN_ACCESS;if(window.DAC_ADMIN_ACCESS_PROMISE)access=await window.DAC_ADMIN_ACCESS_PROMISE;const allowed=access?.role==='owner'||access?.permissions?.siteEditor===true;if(allowed)buildPanel();}
enable();
})();
