const JOB_TYPES=new Set(['residential','commercial','federal']);
const COMMERCIAL_CATEGORIES=new Set(['retail','medical','auto-dealerships','general']);
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
function clean(value,max=160){return String(value||'').trim().slice(0,max);}
function cleanType(value){const type=clean(value,40).toLowerCase();return JOB_TYPES.has(type)?type:'';}
function cleanCommercialCategory(value){const category=clean(value,60).toLowerCase();return COMMERCIAL_CATEGORIES.has(category)?category:'general';}
function projectFromObject(object){const meta=object.customMetadata||{};const jobType=cleanType(meta.jobType)||'commercial';return{id:meta.id||object.key.slice('projects/'.length).replace(/\.json$/,''),name:meta.name||'Untitled Project',jobType,commercialCategory:jobType==='commercial'?cleanCommercialCategory(meta.commercialCategory):'',description:meta.description||'',createdAt:meta.createdAt||''};}
async function listProjects(bucket){let cursor;const projects=[];do{const page=await bucket.list({prefix:'projects/',limit:1000,cursor,include:['customMetadata']});for(const object of page.objects)projects.push(projectFromObject(object));cursor=page.truncated?page.cursor:undefined;}while(cursor);return projects.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));}
function errorResponse(error,fallback='Project request failed.'){const message=error instanceof Error?error.message:String(error||fallback);console.error(JSON.stringify({event:'project_api_error',message}));return json({error:message||fallback},500);}
export async function onRequestGet(context){try{if(!context.env.GALLERY_BUCKET)return json({error:'Gallery storage is not configured.'},503);return json({projects:await listProjects(context.env.GALLERY_BUCKET)});}catch(error){return errorResponse(error,'Could not load projects.');}}
export async function onRequestPost(context){try{if(!context.env.GALLERY_BUCKET)return json({error:'Gallery storage is not configured.'},503);let body;try{body=await context.request.json();}catch{return json({error:'Invalid project request.'},400);}const name=clean(body.name,120);const jobType=cleanType(body.jobType);const commercialCategory=jobType==='commercial'?cleanCommercialCategory(body.commercialCategory):'';const description=clean(body.description,240);if(!name)return json({error:'Project name is required.'},400);if(!jobType)return json({error:'Choose Residential, Commercial, or Federal.'},400);const id=crypto.randomUUID();const createdAt=new Date().toISOString();const project={id,name,jobType,commercialCategory,description,createdAt};const key=`projects/${id}.json`;const customMetadata={id,name,jobType,createdAt};if(commercialCategory)customMetadata.commercialCategory=commercialCategory;if(description)customMetadata.description=description;if(context.data?.adminEmail)customMetadata.createdBy=context.data.adminEmail;const saved=await context.env.GALLERY_BUCKET.put(key,JSON.stringify(project),{httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'no-store'},customMetadata});if(!saved)return json({error:'Could not create project.'},500);return json({project},201);}catch(error){return errorResponse(error,'Could not create project.');}}
export async function onRequestPatch(context){try{if(!context.env.GALLERY_BUCKET)return json({error:'Gallery storage is not configured.'},503);const body=await context.request.json();const id=clean(body.id,80);if(!id)return json({error:'Project id is required.'},400);const key=`projects/${id}.json`;const existing=await context.env.GALLERY_BUCKET.head(key);if(!existing)return json({error:'Project not found.'},404);const old=existing.customMetadata||{};const name=clean(body.name??old.name,120);const jobType=cleanType(body.jobType??old.jobType);const commercialCategory=jobType==='commercial'?cleanCommercialCategory(body.commercialCategory??old.commercialCategory):'';const description=clean(body.description??old.description,240);if(!name||!jobType)return json({error:'Project name and job type are required.'},400);const createdAt=old.createdAt||new Date().toISOString();const project={id,name,jobType,commercialCategory,description,createdAt};const customMetadata={...old,id,name,jobType,createdAt};if(commercialCategory)customMetadata.commercialCategory=commercialCategory;else delete customMetadata.commercialCategory;if(description)customMetadata.description=description;else delete customMetadata.description;const saved=await context.env.GALLERY_BUCKET.put(key,JSON.stringify(project),{httpMetadata:{contentType:'application/json; charset=utf-8',cacheControl:'no-store'},customMetadata});if(!saved)return json({error:'Could not save project.'},500);return json({project});}catch(error){return errorResponse(error,'Could not save project.');}}
